name: Publish Egg

on:
  release:
    types:
      - published

jobs:
  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2.0.0
        with:
          deno-version: 1.x
      - run: deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.1.10/mod.ts
      - run: |
          export PATH="/home/runner/.deno/bin:$PATH"
          eggs link --key ${{ secrets.NESTAPIKEY }}
          eggs publish
